import { useState } from 'react';
import { X, Copy, Download, Check, CheckCircle2 } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Badge } from '@/components/ui/badge';
import { cn } from '@/lib/utils';
import { useToast } from '@/hooks/use-toast';

interface RedlineViewProps {
  gap: {
    id: string;
    risk_level: string;
    category: string;
    original_clause: string;
    compliant_rewrite?: string;
    is_applied?: boolean;
  };
  onClose: () => void;
  onMarkApplied?: (gapId: string) => Promise<void>;
}

export function RedlineView({ gap, onClose, onMarkApplied }: RedlineViewProps) {
  const { toast } = useToast();
  const [isApplying, setIsApplying] = useState(false);
  const [copied, setCopied] = useState(false);

  const getRiskBadgeClass = (level: string) => {
    switch (level) {
      case 'critical': return 'risk-badge-critical';
      case 'high': return 'risk-badge-high';
      case 'medium': return 'risk-badge-medium';
      case 'low': return 'risk-badge-low';
      default: return '';
    }
  };

  const copyToClipboard = async () => {
    if (!gap.compliant_rewrite) return;
    
    try {
      await navigator.clipboard.writeText(gap.compliant_rewrite);
      setCopied(true);
      toast({
        title: "Copied!",
        description: "Compliant text copied to clipboard",
      });
      setTimeout(() => setCopied(false), 2000);
    } catch (err) {
      toast({
        title: "Failed to copy",
        description: "Please try again",
        variant: "destructive",
      });
    }
  };

  const downloadAsText = () => {
    if (!gap.compliant_rewrite) return;

    const content = `COMPLIANCE GAP - ${gap.category.toUpperCase()}
Risk Level: ${gap.risk_level.toUpperCase()}

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

ORIGINAL CLAUSE:
${gap.original_clause}

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

COMPLIANT REWRITE:
${gap.compliant_rewrite}

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Generated by AuditEase`;

    const blob = new Blob([content], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `compliance-fix-${gap.category.toLowerCase().replace(/\s+/g, '-')}.txt`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);

    toast({
      title: "Downloaded!",
      description: "Compliance fix saved as text file",
    });
  };

  const handleMarkApplied = async () => {
    if (!onMarkApplied) return;
    
    setIsApplying(true);
    try {
      await onMarkApplied(gap.id);
      toast({
        title: "Marked as Applied",
        description: "This change has been recorded as applied",
      });
      onClose();
    } catch (err) {
      toast({
        title: "Failed to update",
        description: "Please try again",
        variant: "destructive",
      });
    } finally {
      setIsApplying(false);
    }
  };

  // Simple diff display - show original with strikethrough and new with highlight
  const renderDiff = () => {
    if (!gap.compliant_rewrite) {
      return <p className="text-muted-foreground">No compliant rewrite available.</p>;
    }

    return (
      <div className="grid md:grid-cols-2 gap-6">
        {/* Original */}
        <div>
          <h4 className="text-sm font-semibold text-muted-foreground mb-3 flex items-center gap-2">
            <span className="w-3 h-3 rounded-full bg-destructive"></span>
            Original Clause
          </h4>
          <div className="bg-destructive/5 border border-destructive/20 rounded-lg p-4">
            <p className="text-sm leading-relaxed line-through text-destructive/80 decoration-destructive/50">
              {gap.original_clause}
            </p>
          </div>
        </div>

        {/* Compliant Rewrite */}
        <div>
          <h4 className="text-sm font-semibold text-muted-foreground mb-3 flex items-center gap-2">
            <span className="w-3 h-3 rounded-full bg-success"></span>
            Compliant Rewrite
          </h4>
          <div className="bg-success/5 border border-success/20 rounded-lg p-4">
            <p className="text-sm leading-relaxed text-success">
              {gap.compliant_rewrite}
            </p>
          </div>
        </div>
      </div>
    );
  };

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-4">
      {/* Backdrop */}
      <div 
        className="absolute inset-0 bg-background/80 backdrop-blur-sm"
        onClick={onClose}
      />
      
      {/* Modal */}
      <div className="relative w-full max-w-4xl max-h-[90vh] overflow-auto bg-card rounded-xl shadow-xl animate-scale-in">
        {/* Header */}
        <div className="sticky top-0 flex items-center justify-between p-4 border-b border-border bg-card z-10">
          <div className="flex items-center gap-3">
            <h2 className="text-lg font-semibold">Auto-Redline View</h2>
            <Badge className={getRiskBadgeClass(gap.risk_level)}>
              {gap.risk_level.toUpperCase()}
            </Badge>
            <Badge variant="outline">{gap.category}</Badge>
            {gap.is_applied && (
              <Badge className="bg-success/10 text-success border-success/20">
                <CheckCircle2 className="h-3 w-3 mr-1" />
                Applied
              </Badge>
            )}
          </div>
          <Button variant="ghost" size="icon" onClick={onClose}>
            <X className="h-5 w-5" />
          </Button>
        </div>

        {/* Content */}
        <div className="p-6">
          {renderDiff()}

          {/* Legend */}
          <div className="mt-8 pt-6 border-t border-border">
            <h4 className="text-sm font-medium text-muted-foreground mb-3">Track Changes Legend</h4>
            <div className="flex flex-wrap gap-6 text-sm">
              <div className="flex items-center gap-2">
                <span className="px-2 py-1 rounded bg-destructive/10 line-through text-destructive/80">
                  Deleted text
                </span>
              </div>
              <div className="flex items-center gap-2">
                <span className="px-2 py-1 rounded bg-success/10 text-success">
                  Added text
                </span>
              </div>
            </div>
          </div>
        </div>

        {/* Footer */}
        <div className="sticky bottom-0 flex items-center justify-between gap-3 p-4 border-t border-border bg-card">
          <div className="flex items-center gap-2">
            <Button 
              variant="outline" 
              size="sm"
              onClick={copyToClipboard}
              disabled={!gap.compliant_rewrite}
            >
              {copied ? <Check className="h-4 w-4 mr-2" /> : <Copy className="h-4 w-4 mr-2" />}
              {copied ? "Copied!" : "Copy Rewrite"}
            </Button>
            <Button 
              variant="outline" 
              size="sm"
              onClick={downloadAsText}
              disabled={!gap.compliant_rewrite}
            >
              <Download className="h-4 w-4 mr-2" />
              Download
            </Button>
          </div>
          
          <div className="flex items-center gap-2">
            <Button variant="outline" onClick={onClose}>
              Close
            </Button>
            {!gap.is_applied && onMarkApplied && (
              <Button 
                onClick={handleMarkApplied}
                disabled={isApplying || !gap.compliant_rewrite}
              >
                <CheckCircle2 className="h-4 w-4 mr-2" />
                {isApplying ? "Saving..." : "Mark as Applied"}
              </Button>
            )}
          </div>
        </div>
      </div>
    </div>
  );
}
